/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VehiculesRouteImport } from './routes/vehicules'
import { Route as ConfirmationReferenceRouteImport } from './routes/confirmation.$reference'
import { Route as ReserverIdRouteImport } from './routes/reserver.$id'
import { Route as VehiculesIdRouteImport } from './routes/vehicules.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VehiculesRoute = VehiculesRouteImport.update({
  id: '/vehicules',
  path: '/vehicules',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmationReferenceRoute = ConfirmationReferenceRouteImport.update({
  id: '/confirmation/$reference',
  path: '/confirmation/$reference',
  getParentRoute: () => rootRouteImport,
} as any)
const ReserverIdRoute = ReserverIdRouteImport.update({
  id: '/reserver/$id',
  path: '/reserver/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const VehiculesIdRoute = VehiculesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => VehiculesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/vehicules': typeof VehiculesRouteWithChildren
  '/confirmation/$reference': typeof ConfirmationReferenceRoute
  '/reserver/$id': typeof ReserverIdRoute
  '/vehicules/$id': typeof VehiculesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/vehicules': typeof VehiculesRouteWithChildren
  '/confirmation/$reference': typeof ConfirmationReferenceRoute
  '/reserver/$id': typeof ReserverIdRoute
  '/vehicules/$id': typeof VehiculesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/vehicules': typeof VehiculesRouteWithChildren
  '/confirmation/$reference': typeof ConfirmationReferenceRoute
  '/reserver/$id': typeof ReserverIdRoute
  '/vehicules/$id': typeof VehiculesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/vehicules'
    | '/confirmation/$reference'
    | '/reserver/$id'
    | '/vehicules/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/vehicules'
    | '/confirmation/$reference'
    | '/reserver/$id'
    | '/vehicules/$id'
  id:
    | '__root__'
    | '/'
    | '/vehicules'
    | '/confirmation/$reference'
    | '/reserver/$id'
    | '/vehicules/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  VehiculesRoute: typeof VehiculesRouteWithChildren
  ConfirmationReferenceRoute: typeof ConfirmationReferenceRoute
  ReserverIdRoute: typeof ReserverIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicules': {
      id: '/vehicules'
      path: '/vehicules'
      fullPath: '/vehicules'
      preLoaderRoute: typeof VehiculesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmation/$reference': {
      id: '/confirmation/$reference'
      path: '/confirmation/$reference'
      fullPath: '/confirmation/$reference'
      preLoaderRoute: typeof ConfirmationReferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reserver/$id': {
      id: '/reserver/$id'
      path: '/reserver/$id'
      fullPath: '/reserver/$id'
      preLoaderRoute: typeof ReserverIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicules/$id': {
      id: '/vehicules/$id'
      path: '/$id'
      fullPath: '/vehicules/$id'
      preLoaderRoute: typeof VehiculesIdRouteImport
      parentRoute: typeof VehiculesRoute
    }
  }
}

interface VehiculesRouteChildren {
  VehiculesIdRoute: typeof VehiculesIdRoute
}

const VehiculesRouteChildren: VehiculesRouteChildren = {
  VehiculesIdRoute: VehiculesIdRoute,
}

const VehiculesRouteWithChildren = VehiculesRoute._addFileChildren(
  VehiculesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  VehiculesRoute: VehiculesRouteWithChildren,
  ConfirmationReferenceRoute: ConfirmationReferenceRoute,
  ReserverIdRoute: ReserverIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
