/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CommentCaMarcheRouteImport } from './routes/comment-ca-marche'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as VehiculesRouteImport } from './routes/vehicules'
import { Route as ConfirmationReferenceRouteImport } from './routes/confirmation.$reference'
import { Route as ReserverIdRouteImport } from './routes/reserver.$id'
import { Route as VehiculesIdRouteImport } from './routes/vehicules.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CommentCaMarcheRoute = CommentCaMarcheRouteImport.update({
  id: '/comment-ca-marche',
  path: '/comment-ca-marche',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const VehiculesRoute = VehiculesRouteImport.update({
  id: '/vehicules',
  path: '/vehicules',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmationReferenceRoute = ConfirmationReferenceRouteImport.update({
  id: '/confirmation/$reference',
  path: '/confirmation/$reference',
  getParentRoute: () => rootRouteImport,
} as any)
const ReserverIdRoute = ReserverIdRouteImport.update({
  id: '/reserver/$id',
  path: '/reserver/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const VehiculesIdRoute = VehiculesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => VehiculesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/auth': typeof AuthRoute
  '/comment-ca-marche': typeof CommentCaMarcheRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/vehicules': typeof VehiculesRouteWithChildren
  '/confirmation/$reference': typeof ConfirmationReferenceRoute
  '/reserver/$id': typeof ReserverIdRoute
  '/vehicules/$id': typeof VehiculesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/auth': typeof AuthRoute
  '/comment-ca-marche': typeof CommentCaMarcheRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/vehicules': typeof VehiculesRouteWithChildren
  '/confirmation/$reference': typeof ConfirmationReferenceRoute
  '/reserver/$id': typeof ReserverIdRoute
  '/vehicules/$id': typeof VehiculesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/auth': typeof AuthRoute
  '/comment-ca-marche': typeof CommentCaMarcheRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/vehicules': typeof VehiculesRouteWithChildren
  '/confirmation/$reference': typeof ConfirmationReferenceRoute
  '/reserver/$id': typeof ReserverIdRoute
  '/vehicules/$id': typeof VehiculesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/auth'
    | '/comment-ca-marche'
    | '/contact'
    | '/faq'
    | '/privacy'
    | '/terms'
    | '/vehicules'
    | '/confirmation/$reference'
    | '/reserver/$id'
    | '/vehicules/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/auth'
    | '/comment-ca-marche'
    | '/contact'
    | '/faq'
    | '/privacy'
    | '/terms'
    | '/vehicules'
    | '/confirmation/$reference'
    | '/reserver/$id'
    | '/vehicules/$id'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/auth'
    | '/comment-ca-marche'
    | '/contact'
    | '/faq'
    | '/privacy'
    | '/terms'
    | '/vehicules'
    | '/confirmation/$reference'
    | '/reserver/$id'
    | '/vehicules/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  AuthRoute: typeof AuthRoute
  CommentCaMarcheRoute: typeof CommentCaMarcheRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  VehiculesRoute: typeof VehiculesRouteWithChildren
  ConfirmationReferenceRoute: typeof ConfirmationReferenceRoute
  ReserverIdRoute: typeof ReserverIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comment-ca-marche': {
      id: '/comment-ca-marche'
      path: '/comment-ca-marche'
      fullPath: '/comment-ca-marche'
      preLoaderRoute: typeof CommentCaMarcheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicules': {
      id: '/vehicules'
      path: '/vehicules'
      fullPath: '/vehicules'
      preLoaderRoute: typeof VehiculesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmation/$reference': {
      id: '/confirmation/$reference'
      path: '/confirmation/$reference'
      fullPath: '/confirmation/$reference'
      preLoaderRoute: typeof ConfirmationReferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reserver/$id': {
      id: '/reserver/$id'
      path: '/reserver/$id'
      fullPath: '/reserver/$id'
      preLoaderRoute: typeof ReserverIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicules/$id': {
      id: '/vehicules/$id'
      path: '/$id'
      fullPath: '/vehicules/$id'
      preLoaderRoute: typeof VehiculesIdRouteImport
      parentRoute: typeof VehiculesRoute
    }
  }
}

interface VehiculesRouteChildren {
  VehiculesIdRoute: typeof VehiculesIdRoute
}

const VehiculesRouteChildren: VehiculesRouteChildren = {
  VehiculesIdRoute: VehiculesIdRoute,
}

const VehiculesRouteWithChildren = VehiculesRoute._addFileChildren(
  VehiculesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  AuthRoute: AuthRoute,
  CommentCaMarcheRoute: CommentCaMarcheRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  VehiculesRoute: VehiculesRouteWithChildren,
  ConfirmationReferenceRoute: ConfirmationReferenceRoute,
  ReserverIdRoute: ReserverIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
